CREATE TABLE IF NOT EXISTS hardwares (
  id SERIAL PRIMARY KEY,
  receipt_date DATE NULL,
  receipt_proof TEXT NULL,
  asset_type TEXT NULL,
  device_activation_date DATE NULL,
  inspection_result TEXT NULL,
  serial_number TEXT NULL,
  model TEXT NULL,
  warranty_start_date DATE NULL,
  warranty_end_date DATE NULL,
  warranty_card_number TEXT NULL,
  device_specifications TEXT NULL,
  asset_status TEXT NULL,
  asset_responsible TEXT NULL,
  storage_location INT NULL,
  usage_period INT NULL,
  asset_out_time DATE NULL,
  asset_condition TEXT NULL,
  purchase_receipt TEXT NULL,
  asset_id INT NULL,
  division_id INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (division_id) REFERENCES divisions (id) ON DELETE CASCADE ON UPDATE CASCADE
);